---
services:
  cappuccino:
    image: "ghcr.io/thereverend403/cappuccino:main"
    container_name: "cappuccino"
    restart: "unless-stopped"
    init: true
    read_only: true
    user: "${CAPPUCCINO_PUID:-${PUID:-1000}}:${CAPPUCCINO_PGID:-${PGID:-1000}}"
    depends_on:
      db-18:
        condition: "service_healthy"
    env_file:
      - path: ".env"
        required: false
      - path: "stack.env"
        required: false
    environment:
      TZ: "${TZ:-UTC}"
      CFG_BOT_NICK: "${CFG_BOT_NICK:?}"
      CFG_BOT_REALNAME: "${CFG_BOT_REALNAME:-cappuccino}"
      CFG_BOT_USERNAME: "${CFG_BOT_USERNAME:-cappuccino}"
      CFG_IRC_HOST: "${CFG_IRC_HOST:?}"
      CFG_IRC_PORT: "${CFG_IRC_PORT:-6697}"
      CFG_IRC_SSL: "${CFG_IRC_SSL:-true}"
      CFG_BOT_ADMIN: "${CFG_BOT_ADMIN:?}"
      CFG_DB_URI: "${CFG_DB_URI:-postgresql+psycopg://${POSTGRES_USER:-cappuccino}:${POSTGRES_PASSWORD:-cappuccino}@/${POSTGRES_DB:-cappuccino}?host=${POSTGRES_HOST:-/run/postgresql}}"
    volumes:
      - "postgres_18_socket:/run/postgresql"
      - "${BASE_DIR:-.}/config/cappuccino:/config"
    tmpfs:
      - "/tmp"
    networks:
      - "cappuccino"
    deploy:
      resources:
        limits:
          cpus: "${CAPPUCCINO_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${CAPPUCCINO_MEM_LIMIT:-${MEM_LIMIT:-0}}"

  db-18:
    image: "postgres:18-alpine"
    container_name: "cappuccino_db_18"
    restart: "unless-stopped"
    init: true
    user: "${POSTGRES_PUID:-${PUID:-1000}}:${POSTGRES_PGID:-${PGID:-1000}}"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    network_mode: "none"
    environment:
      TZ: "${TZ:-UTC}"
      POSTGRES_HOST: "${POSTGRES_HOST:-/run/postgresql}"
      POSTGRES_DB: "${POSTGRES_DB:-cappuccino}"
      POSTGRES_USER: "${POSTGRES_USER:-cappuccino}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-cappuccino}"
    volumes:
      - "${BASE_DIR:-.}/data/db/18:/var/lib/postgresql/18/docker"
      - "${BASE_DIR:-.}/config/db/18:/etc/postgresql"
      - "postgres_18_socket:/run/postgresql"
    tmpfs:
      - "/run"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -q --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER --host=$$POSTGRES_HOST"
      start_period: "10s"
      start_interval: "1s"
      interval: "10s"
      timeout: "5s"
    shm_size: "${SHM_SIZE:-512M}"
    deploy:
      resources:
        limits:
          cpus: "${POSTGRES_CPU_LIMIT:-${CPU_LIMIT:-0}}"
          memory: "${POSTGRES_MEM_LIMIT:-${MEM_LIMIT:-0}}"

volumes:
  postgres_18_socket:

networks:
  cappuccino:
    name: "cappuccino"
